/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TeaCollector;

import entity.Advance;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import jpaControls.AdvanceJpaController;
import jpaControls.SupplierJpaController;

/**
 *
 * @author jayantha
 */
public class AdvanceUI extends javax.swing.JFrame {

    Connection conn = LoginUI.conn;
    ResultSet RS = null;
    PreparedStatement PST = null;
    String time;

    AdvanceJpaController advanceJpaController = new AdvanceJpaController(Persistence.createEntityManagerFactory("TeaCollectorPU"));
    SupplierJpaController supplierJpaController = new SupplierJpaController(Persistence.createEntityManagerFactory("TeaCollectorPU"));

    public AdvanceUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog3 = new datechooser.beans.DateChooserDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnl_record = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        txt_supID1 = new javax.swing.JTextField();
        txt_amount1 = new javax.swing.JTextField();
        spin_NoOfMnt = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_record = new javax.swing.JTable();
        btn_add1 = new javax.swing.JButton();
        btn_delete1 = new javax.swing.JButton();
        btn_update1 = new javax.swing.JButton();
        date_start1 = new com.toedter.calendar.JDateChooser();
        btn_clear1 = new javax.swing.JButton();
        pnl_viwAdv = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_viewAll = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_supID2 = new javax.swing.JTextField();
        txt_amount2 = new javax.swing.JTextField();
        txt_paid2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_delete2 = new javax.swing.JButton();
        btn_update2 = new javax.swing.JButton();
        date_start2 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txt_noOfMnt2 = new javax.swing.JTextField();
        btn_clearr2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 650));

        jLabel6.setFont(new java.awt.Font("Andalus", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Advance");

        pnl_record.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pnl_recordComponentShown(evt);
            }
        });

        jLabel14.setText("Supplier No :");

        jLabel15.setText("Supplier Name :");

        jLabel16.setText("Amount :");

        jLabel17.setText("Start Month :");

        jLabel18.setText("No of Month :");

        lbl_name.setText("- - -");

        tbl_record.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier No", "Supplier Name", "Amount", "Start Month", "No of Month", "recordID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_recordMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_record);
        if (tbl_record.getColumnModel().getColumnCount() > 0) {
            tbl_record.getColumnModel().getColumn(0).setResizable(false);
            tbl_record.getColumnModel().getColumn(1).setResizable(false);
            tbl_record.getColumnModel().getColumn(2).setResizable(false);
            tbl_record.getColumnModel().getColumn(3).setResizable(false);
            tbl_record.getColumnModel().getColumn(4).setResizable(false);
        }

        btn_add1.setText("ADD");
        btn_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add1ActionPerformed(evt);
            }
        });

        btn_delete1.setText("Delete");
        btn_delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete1ActionPerformed(evt);
            }
        });

        btn_update1.setText("Update");
        btn_update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update1ActionPerformed(evt);
            }
        });

        date_start1.setDateFormatString("yyyy-MM-dd");

        btn_clear1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clear1.setLabel("Clear");
        btn_clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_recordLayout = new javax.swing.GroupLayout(pnl_record);
        pnl_record.setLayout(pnl_recordLayout);
        pnl_recordLayout.setHorizontalGroup(
            pnl_recordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_recordLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnl_recordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_recordLayout.createSequentialGroup()
                        .addGroup(pnl_recordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGroup(pnl_recordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_recordLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(txt_supID1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_recordLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pnl_recordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_name)
                                    .addComponent(spin_NoOfMnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(date_start1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(txt_amount1)))))
                    .addGroup(pnl_recordLayout.createSequentialGroup()
                        .addComponent(btn_add1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_update1))
                    .addComponent(btn_clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_recordLayout.setVerticalGroup(
            pnl_recordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_recordLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(pnl_recordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_recordLayout.createSequentialGroup()
                        .addGroup(pnl_recordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_supID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_recordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(lbl_name))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17))
                    .addGroup(pnl_recordLayout.createSequentialGroup()
                        .addComponent(txt_amount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(date_start1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnl_recordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(spin_NoOfMnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnl_recordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_recordLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pnl_recordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_update1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_add1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_recordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Record Advance", pnl_record);

        pnl_viwAdv.setMinimumSize(new java.awt.Dimension(0, 0));
        pnl_viwAdv.setPreferredSize(new java.awt.Dimension(950, 650));
        pnl_viwAdv.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pnl_viwAdvComponentShown(evt);
            }
        });

        tbl_viewAll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Supplier ID", "Amount", "Paid", "Remaining amount", "Start Month", "No of Month"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_viewAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_viewAllMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_viewAll);

        jLabel1.setText("Supplier ID :");

        jLabel2.setText("Amount :");

        jLabel3.setText("Paid :");

        jLabel4.setText("Start Month :");

        btn_delete2.setText("Delete");
        btn_delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete2ActionPerformed(evt);
            }
        });

        btn_update2.setText("Update");
        btn_update2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update2ActionPerformed(evt);
            }
        });

        date_start2.setDateFormatString("yyyy-MM-dd");

        jLabel7.setText("No of Month :");

        btn_clearr2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clearr2.setLabel("Clear");
        btn_clearr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearr2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_viwAdvLayout = new javax.swing.GroupLayout(pnl_viwAdv);
        pnl_viwAdv.setLayout(pnl_viwAdvLayout);
        pnl_viwAdvLayout.setHorizontalGroup(
            pnl_viwAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_viwAdvLayout.createSequentialGroup()
                .addGroup(pnl_viwAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_viwAdvLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4))
                    .addGroup(pnl_viwAdvLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnl_viwAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_viwAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_viwAdvLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(33, 33, 33))
                                .addGroup(pnl_viwAdvLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(43, 43, 43)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_viwAdvLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)))
                        .addGroup(pnl_viwAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_supID2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_paid2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(txt_amount2))
                        .addGap(63, 63, 63)
                        .addGroup(pnl_viwAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_viwAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date_start2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_noOfMnt2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addComponent(btn_delete2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_update2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_clearr2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_viwAdvLayout.setVerticalGroup(
            pnl_viwAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_viwAdvLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnl_viwAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_viwAdvLayout.createSequentialGroup()
                        .addGroup(pnl_viwAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_viwAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_supID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel4))
                            .addComponent(date_start2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_viwAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_viwAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_amount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGroup(pnl_viwAdvLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(pnl_viwAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txt_noOfMnt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_viwAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_paid2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_viwAdvLayout.createSequentialGroup()
                        .addGroup(pnl_viwAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_viwAdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_update2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_clearr2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_delete2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("View Advance", null, pnl_viwAdv, "");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(377, 377, 377)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete1ActionPerformed
        if (AdvId != 0) {
            try {
                advanceJpaController.destroy(AdvId);
                txt_amount1.setText("");
                txt_supID1.setText("");
                spin_NoOfMnt.setValue(Integer.valueOf("1"));                
                lbl_name.setText("");
                AdvId = 0;
                JOptionPane.showMessageDialog(null, "Data Deleted..");                
                pnl_recordComponentShown(null);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Cant delete.." + e);
            }

        } else {
            JOptionPane.showMessageDialog(null, "AdvId = 0");
        }
    }//GEN-LAST:event_btn_delete1ActionPerformed

    private void btn_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add1ActionPerformed
        // TODO add your handling code here:
        Advance advance = new Advance();

        advance.setSupplierID(supplierJpaController.findSupplier(Integer.parseInt(txt_supID1.getText())));
        advance.setAmount(Integer.parseInt(txt_amount1.getText()));
        advance.setStartMonth(date_start1.getDate());

        advance.setTimeMonth((Integer) spin_NoOfMnt.getValue());
        advance.setPaid(0);
        advance.setStatus(true);

        try {
            advanceJpaController.create(advance);
            JOptionPane.showMessageDialog(null, "Data seved..");
            txt_amount1.setText("");
            txt_supID1.setText("");
            spin_NoOfMnt.setValue(Integer.valueOf("1"));
            lbl_name.setText("");
            pnl_recordComponentShown(null);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Somthing wrong... " + e);
        }
    }//GEN-LAST:event_btn_add1ActionPerformed

    private void btn_update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update1ActionPerformed
        if (AdvId != 0) {
            Advance advance = advanceJpaController.findAdvance(AdvId);

            advance.setSupplierID(supplierJpaController.findSupplier(Integer.parseInt(txt_supID1.getText())));
            advance.setAmount(Integer.parseInt(txt_amount1.getText()));
            advance.setStartMonth(date_start1.getDate());
            advance.setTimeMonth((Integer) spin_NoOfMnt.getValue());

            try {
                advanceJpaController.edit(advance);
                JOptionPane.showMessageDialog(null, "Data Updated..");
                txt_amount1.setText("");
                txt_supID1.setText("");
                spin_NoOfMnt.setValue(Integer.valueOf("1"));
                lbl_name.setText("");
                pnl_recordComponentShown(null);
            } catch (Exception ex) {
                Logger.getLogger(AdvanceUI.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Somthing wrong... " + ex);

            }

        } else {

            JOptionPane.showMessageDialog(null, "Adv id = 0");

        }
    }//GEN-LAST:event_btn_update1ActionPerformed

    private void tbl_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_recordMouseClicked
        int i = tbl_record.getSelectedRow();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");

        TableModel model = tbl_record.getModel();

        txt_supID1.setText(model.getValueAt(i, 0).toString());
        lbl_name.setText(model.getValueAt(i, 1).toString());
        txt_amount1.setText(model.getValueAt(i, 2).toString());
        date_start1.setDate(Date.valueOf(simpleDateFormat.format(Date.valueOf(model.getValueAt(i, 3).toString()))));
        spin_NoOfMnt.setValue(Integer.valueOf(model.getValueAt(i, 4).toString()));
        AdvId = (int) model.getValueAt(i, 5);
    }//GEN-LAST:event_tbl_recordMouseClicked

    private void pnl_viwAdvComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnl_viwAdvComponentShown
        
        List<entity.Advance> advanceEntity = advanceJpaController.findAdvanceEntities();
        DefaultTableModel model = (DefaultTableModel) tbl_viewAll.getModel();
        model.setRowCount(0);
        Object[] row = new Object[7];
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");

        for (int i = 0; i < advanceEntity.size(); i++) {

            row[0] = advanceEntity.get(i).getAdvId();
            row[1] = advanceEntity.get(i).getSupplierID().getId();
            row[2] = advanceEntity.get(i).getAmount();
            row[3] = advanceEntity.get(i).getPaid();
            row[4] = Integer.parseInt(row[2].toString()) - Integer.parseInt(row[3].toString());
            row[5] = simpleDateFormat.format(advanceEntity.get(i).getStartMonth());
            row[6] = advanceEntity.get(i).getTimeMonth();

            model.addRow(row);

        }
    }//GEN-LAST:event_pnl_viwAdvComponentShown

    private void pnl_recordComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnl_recordComponentShown
        List<entity.Advance> advanceEntity = advanceJpaController.findAdvanceEntities();
        DefaultTableModel model = (DefaultTableModel) tbl_record.getModel();
        model.setRowCount(0);
        Object[] row = new Object[6];
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");

        for (int i = 0; i < advanceEntity.size(); i++) {

            row[0] = advanceEntity.get(i).getSupplierID().getId();
            row[1] = advanceEntity.get(i).getSupplierID().getName();
            row[2] = advanceEntity.get(i).getAmount();
            row[3] = simpleDateFormat.format(advanceEntity.get(i).getStartMonth());
            row[4] = advanceEntity.get(i).getTimeMonth();
            row[5] = advanceEntity.get(i).getAdvId();

            model.addRow(row);

        }
    }//GEN-LAST:event_pnl_recordComponentShown

    private void tbl_viewAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_viewAllMouseClicked
        int i = tbl_viewAll.getSelectedRow();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");

        TableModel model = tbl_viewAll.getModel();

        AdvId = (int) model.getValueAt(i, 0);
        txt_supID2.setText(model.getValueAt(i, 1).toString());
        txt_amount2.setText(model.getValueAt(i, 2).toString());
        txt_paid2.setText(model.getValueAt(i, 3).toString());
        date_start2.setDate(Date.valueOf(simpleDateFormat.format(Date.valueOf(model.getValueAt(i, 5).toString()))));
        txt_noOfMnt2.setText(model.getValueAt(i, 6).toString());
        
    }//GEN-LAST:event_tbl_viewAllMouseClicked

    private void btn_delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete2ActionPerformed
        if (AdvId != 0) {
            try {
                advanceJpaController.destroy(AdvId);
                txt_supID2.setText("");
                txt_amount2.setText("");
                txt_paid2.setText("");
                date_start2.setDate(null);
                txt_noOfMnt2.setText("");
                AdvId = 0;
                JOptionPane.showMessageDialog(null, "Data Deleted..");                
                pnl_viwAdvComponentShown(null);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Cant delete.." + e);
            }

        } else {
            JOptionPane.showMessageDialog(null, "AdvId = 0");
        }
    }//GEN-LAST:event_btn_delete2ActionPerformed

    private void btn_update2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update2ActionPerformed
        if (AdvId != 0) {
            Advance advance = advanceJpaController.findAdvance(AdvId);

            advance.setSupplierID(supplierJpaController.findSupplier(Integer.parseInt(txt_supID2.getText())));
            advance.setAmount(Integer.parseInt(txt_amount2.getText()));
            advance.setPaid(Integer.parseInt(txt_paid2.getText()));
            advance.setStartMonth(date_start2.getDate());
            advance.setTimeMonth(Integer.parseInt(txt_noOfMnt2.getText()));

            try {
                advanceJpaController.edit(advance);
                JOptionPane.showMessageDialog(null, "Data Updated..");
                txt_amount2.setText("");
                txt_supID2.setText("");
                txt_paid2.setText("");
                date_start2.setDate(null);
                txt_noOfMnt2.setText("");
                
                AdvId=0;
                pnl_viwAdvComponentShown(null);
                
            } catch (Exception ex) {
                Logger.getLogger(AdvanceUI.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Somthing wrong... " + ex);

            }

        } else {

            JOptionPane.showMessageDialog(null, "Adv id = 0");

        }
    }//GEN-LAST:event_btn_update2ActionPerformed

    private void btn_clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear1ActionPerformed
        txt_supID1.setText("");
        lbl_name.setText("");
        txt_amount1.setText("");
        date_start1.setDate(null);
        spin_NoOfMnt.setValue(Integer.valueOf("1"));
        AdvId = 0;
    }//GEN-LAST:event_btn_clear1ActionPerformed

    private void btn_clearr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearr2ActionPerformed
        txt_supID2.setText("");
        txt_amount2.setText("");
        txt_paid2.setText("");
        date_start2.setDate(null);
        txt_noOfMnt2.setText("");
        AdvId = 0;
    }//GEN-LAST:event_btn_clearr2ActionPerformed


//    public ArrayList<AdvanceRecord> getAdvanveRecordList() {
//        ArrayList<AdvanceRecord> recordList = new ArrayList<AdvanceRecord>();
//        String query = "select * from advance where paid=0";
//
//        try {
//            RS = conn.prepareStatement(query).executeQuery();
//            AdvanceRecord dReco;
//            while (RS.next()) {
//                dReco = new AdvanceRecord(RS.getInt("adv_id"), RS.getInt("supplierID"), RS.getInt("amount"), RS.getInt("paid"), RS.getInt("status"), RS.getString("startMonth"), RS.getInt("time_month"), RS.getString("added_by"), RS.getString("added_on"));
//                recordList.add(dReco);
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
//        return recordList;
//    }

//    public ArrayList<AdvanceRecord> getAdvanveRecordfullList() {
//        ArrayList<AdvanceRecord> recordList = new ArrayList<AdvanceRecord>();
//        String query = "select * from advance";
//
//        try {
//            RS = conn.prepareStatement(query).executeQuery();
//            AdvanceRecord dReco;
//            while (RS.next()) {
//                dReco = new AdvanceRecord(
//                        RS.getInt("adv_id"),
//                        RS.getInt("supplierID"),
//                        RS.getInt("amount"),
//                        RS.getInt("paid"),
//                        RS.getInt("status"),
//                        RS.getString("startMonth"),
//                        RS.getInt("time_month"),
//                        RS.getString("added_by"),
//                        RS.getString("added_on"));
//                recordList.add(dReco);
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
//        return recordList;
//    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvanceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvanceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvanceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvanceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdvanceUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add1;
    private javax.swing.JButton btn_clear1;
    private javax.swing.JButton btn_clearr2;
    private javax.swing.JButton btn_delete1;
    private javax.swing.JButton btn_delete2;
    private javax.swing.JButton btn_update1;
    private javax.swing.JButton btn_update2;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private datechooser.beans.DateChooserDialog dateChooserDialog3;
    private com.toedter.calendar.JDateChooser date_start1;
    private com.toedter.calendar.JDateChooser date_start2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JPanel pnl_record;
    private javax.swing.JPanel pnl_viwAdv;
    private javax.swing.JSpinner spin_NoOfMnt;
    private javax.swing.JTable tbl_record;
    private javax.swing.JTable tbl_viewAll;
    private javax.swing.JTextField txt_amount1;
    private javax.swing.JTextField txt_amount2;
    private javax.swing.JTextField txt_noOfMnt2;
    private javax.swing.JTextField txt_paid2;
    private javax.swing.JTextField txt_supID1;
    private javax.swing.JTextField txt_supID2;
    // End of variables declaration//GEN-END:variables
    private int AdvId = 0;

}
