/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TeaCollector;

import entity.Supplier;
import entity.TeaPacket;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import jpaControls.SupplierJpaController;
import jpaControls.TeaPacketJpaController;

/**
 *
 * @author jayantha
 */
public class Tea_packet extends javax.swing.JFrame {

    Connection conn = LoginUI.conn;
    ResultSet RS = null;

    TeaPacketJpaController teaPacketJpaController = new TeaPacketJpaController(Persistence.createEntityManagerFactory("TeaCollectorPU"));
    SupplierJpaController supplierJpaController = new SupplierJpaController(Persistence.createEntityManagerFactory("TeaCollectorPU"));

    public Tea_packet() {
        initComponents();
        loadTodayData_tblTeaPacket();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_teaPacket = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JTextField();
        lbl_name = new javax.swing.JLabel();
        txt_supID = new javax.swing.JTextField();
        btn_delete = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        date_date = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        date_serchDate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        day_1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        day_2 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_serchRecord = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_quantity_tab2 = new javax.swing.JTextField();
        date_updateDate = new com.toedter.calendar.JDateChooser();
        btn_update_tab2 = new javax.swing.JButton();
        btn_delete_tab2 = new javax.swing.JButton();
        btn_Search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel6.setFont(new java.awt.Font("Andalus", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Tea Packet");

        tbl_teaPacket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier No", "Supplier Name", "Quantity", "Date", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_teaPacket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_teaPacketMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_teaPacket);

        jLabel1.setText("Supplier No : ");

        jLabel2.setText("Supplier Name : ");

        jLabel3.setText("Quantity :");

        jLabel4.setText("Date : ");

        lbl_name.setText("- - -");

        txt_supID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_supIDFocusLost(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_update.setText("Update");
        btn_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_add.setText("Add");
        btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        date_date.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_delete)
                        .addGap(18, 18, 18)
                        .addComponent(btn_update)
                        .addGap(18, 18, 18)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(lbl_name))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_supID)
                            .addComponent(date_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(txt_quantity, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(675, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jLabel1)
                    .addGap(180, 180, 180)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(txt_supID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_name))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(date_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(234, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(0, 459, Short.MAX_VALUE))
                        .addComponent(jScrollPane1))
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Record      ", jPanel2);

        jLabel7.setText("Suppiler ID :");

        jLabel8.setText("Date :");

        date_serchDate.setDateFormatString("yyyy-MM-dd");

        jLabel9.setText("Date Range - Day 01 : ");

        day_1.setDateFormatString("yyyy-MM-dd");

        jLabel10.setText("Day 02 : ");

        day_2.setDateFormatString("yyyy-MM-dd");

        tbl_serchRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier ID", "Supplier Name", "Date", "Quantity", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_serchRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_serchRecordMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_serchRecord);

        jLabel5.setText("Date : ");

        jLabel11.setText("Quantity :");

        date_updateDate.setDateFormatString("yyyy-MM-dd");

        btn_update_tab2.setText("Update");
        btn_update_tab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_tab2ActionPerformed(evt);
            }
        });

        btn_delete_tab2.setText("Delete");
        btn_delete_tab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_tab2ActionPerformed(evt);
            }
        });

        btn_Search.setText("Search");
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel9))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(date_serchDate, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(day_2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(day_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40)
                                .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(date_updateDate, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_quantity_tab2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(337, 337, 337)
                                .addComponent(btn_update_tab2)
                                .addGap(38, 38, 38)
                                .addComponent(btn_delete_tab2)))
                        .addGap(0, 85, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addComponent(day_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel8))
                                .addComponent(jLabel10)
                                .addComponent(day_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(date_serchDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(date_updateDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txt_quantity_tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_update_tab2)
                        .addComponent(btn_delete_tab2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 933, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(9, 9, 9)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("View", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(390, 390, 390))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadTodayData_tblTeaPacket(){
        List<TeaPacket> teaPacketEntities = teaPacketJpaController.findTeaPacketEntities();

        DefaultTableModel model = (DefaultTableModel) tbl_teaPacket.getModel();
        model.setRowCount(0);   //referesh jTable data
        Object[] row = new Object[5];
        
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");

        for (int i = 0; i < teaPacketEntities.size(); i++) {

            row[0] = teaPacketEntities.get(i).getSupplierId().getId();
            row[1] = teaPacketEntities.get(i).getSupplierId().getName();
            row[2] = teaPacketEntities.get(i).getQuantity();
            row[3] = simpleDateFormat.format(teaPacketEntities.get(i).getDate());
            row[4] = teaPacketEntities.get(i).getId();

            model.addRow(row);

        }
        
    }
    
    private void txt_supIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_supIDFocusLost
        Supplier supplier = supplierJpaController.findSupplier(Integer.parseInt(txt_supID.getText()));
        lbl_name.setText(supplier.getName());
    }//GEN-LAST:event_txt_supIDFocusLost

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        TeaPacket teaPacket = new TeaPacket();
        teaPacket.setSupplierId(supplierJpaController.findSupplier(Integer.parseInt(txt_supID.getText().toString())));
        teaPacket.setQuantity(Integer.parseInt(txt_quantity.getText()));
        teaPacket.setDate(date_date.getDate());

        teaPacketJpaController.create(teaPacket);
        
        JOptionPane.showMessageDialog(null, "Data Saved..");
        txt_supID.setText("");
        txt_quantity.setText("");
        lbl_name.setText("");
        
        loadTodayData_tblTeaPacket();

    }//GEN-LAST:event_btn_addActionPerformed

    private void tbl_serchRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_serchRecordMouseClicked
        // Display selected row in text field

        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        int i = tbl_serchRecord.getSelectedRow();
        TableModel model = tbl_serchRecord.getModel();

        date_updateDate.setDate(Date.valueOf(simpleDateFormat.format(Date.valueOf(model.getValueAt(i, 2).toString()))));
        txt_quantity_tab2.setText(model.getValueAt(i, 3).toString());

        serchTableRecordId = Integer.parseInt(model.getValueAt(i, 4).toString());
        JOptionPane.showMessageDialog(this, serchTableRecordId);
    }//GEN-LAST:event_tbl_serchRecordMouseClicked

    private void btn_update_tab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_tab2ActionPerformed
        if (serchTableRecordId != 0) {
            try {
                TeaPacket teaPacket = teaPacketJpaController.findTeaPacket(serchTableRecordId);

                teaPacket.setDate(date_updateDate.getDate());
                teaPacket.setQuantity(Integer.parseInt(txt_quantity_tab2.getText()));

                teaPacketJpaController.edit(teaPacket);
                JOptionPane.showMessageDialog(null, "Record Update!");
                btn_SearchActionPerformed(null);
                
                date_updateDate.setDate(null);
                txt_quantity_tab2.setText("");
                serchTableRecordId = 0;

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "can't Update error " + ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Somthing error.. Record id = 0");
        }
    }//GEN-LAST:event_btn_update_tab2ActionPerformed

    private void btn_delete_tab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_tab2ActionPerformed
        if (serchTableRecordId != 0) {
            try {
                teaPacketJpaController.destroy(serchTableRecordId);
                JOptionPane.showMessageDialog(null, "Record Delete!");
                loadTodayData_tblTeaPacket();
                serchTableRecordId = 0;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "canot delete error " + ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "SOmthing error.. Record id = 0");
        }
    }//GEN-LAST:event_btn_delete_tab2ActionPerformed

    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed

        List<TeaPacket> teaPacketEntities = teaPacketJpaController.findTeaPacketEntities();

        DefaultTableModel model = (DefaultTableModel) tbl_serchRecord.getModel();
        model.setRowCount(0);   //referesh jTable data
        Object[] row = new Object[5];

        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");

        for (int i = 0; i < teaPacketEntities.size(); i++) {

            row[0] = teaPacketEntities.get(i).getSupplierId().getId();
            row[1] = teaPacketEntities.get(i).getSupplierId().getName();
            row[2] = simpleDateFormat.format(teaPacketEntities.get(i).getDate());
            row[3] = teaPacketEntities.get(i).getQuantity();
            row[4] = teaPacketEntities.get(i).getId();

            model.addRow(row);

        }

    }//GEN-LAST:event_btn_SearchActionPerformed

    private void tbl_teaPacketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_teaPacketMouseClicked
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");

        int i = tbl_teaPacket.getSelectedRow();
        TableModel model = tbl_teaPacket.getModel();
        txt_supID.setText(model.getValueAt(i, 0).toString());
        lbl_name.setText(model.getValueAt(i, 1).toString());
        txt_quantity.setText(model.getValueAt(i, 2).toString());
        date_date.setDate(Date.valueOf(simpleDateFormat.format(Date.valueOf(model.getValueAt(i, 3).toString()))));
        tableTeaPacketId = (int) model.getValueAt(i, 4);
    }//GEN-LAST:event_tbl_teaPacketMouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        if(tableTeaPacketId != 0){
            TeaPacket teaPacket = teaPacketJpaController.findTeaPacket(tableTeaPacketId);
            
            Supplier supplier = supplierJpaController.findSupplier(Integer.parseInt(txt_supID.getText()));            
            teaPacket.setSupplierId(supplier);
            teaPacket.setQuantity(Integer.parseInt(txt_quantity.getText()));
            teaPacket.setDate(date_date.getDate());
            
            try {
                teaPacketJpaController.edit(teaPacket);
                loadTodayData_tblTeaPacket();
                tableTeaPacketId=0;
                
            } catch (Exception ex) {
                Logger.getLogger(Tea_packet.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);                
            }
        }else{            
                JOptionPane.showMessageDialog(null, "Error..! TeaPacketId = 0");                
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        if (tableTeaPacketId != 0) {
            try {
                teaPacketJpaController.destroy(tableTeaPacketId);
                JOptionPane.showMessageDialog(null, "Record Delete!");
                tableTeaPacketId = 0;
                loadTodayData_tblTeaPacket();
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "canot delete error " + ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "SOmthing error.. Record id = 0");
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tea_packet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tea_packet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tea_packet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tea_packet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tea_packet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Search;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_delete_tab2;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_update_tab2;
    private com.toedter.calendar.JDateChooser date_date;
    private com.toedter.calendar.JDateChooser date_serchDate;
    private com.toedter.calendar.JDateChooser date_updateDate;
    private com.toedter.calendar.JDateChooser day_1;
    private com.toedter.calendar.JDateChooser day_2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JTable tbl_serchRecord;
    private javax.swing.JTable tbl_teaPacket;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JTextField txt_quantity_tab2;
    private javax.swing.JTextField txt_supID;
    // End of variables declaration//GEN-END:variables
    private int serchTableRecordId = 0;
    private int tableTeaPacketId = 0;
    /* 
    private ArrayList<Tea_packetRecord> getTeaPacketRecordFullList() {
        ArrayList<Tea_packetRecord> recordList = new ArrayList<Tea_packetRecord>();
        String query = "select * from tea_packet";

        try {
            RS = conn.prepareStatement(query).executeQuery();
            Tea_packetRecord dReco;
            while (RS.next()) {
                dReco = new Tea_packetRecord(
                        RS.getInt("id"),
                        RS.getString("name"),
                        RS.getDouble("price"),
                        RS.getString("valid_from"),
                        RS.getString("added_by"),
                        RS.getString("added_on"),
                        RS.getString("added_at"));
                recordList.add(dReco);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return recordList;
    }
     */
}
